# Generated by Django 2.2.6 on 2020-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='selected_cateror',
            field=models.CharField(default='Not selected', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='selected_decorator',
            field=models.CharField(default='Not selected', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='selected_hotel',
            field=models.CharField(default='Not selected', max_length=200),
        ),
    ]
