# Generated by Django 2.2.6 on 2020-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0004_auto_20200429_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall_rent',
            field=models.FloatField(),
        ),
    ]
