# Generated by Django 2.2.6 on 2020-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0006_auto_20200429_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=200)),
                ('person_capacity', models.IntegerField()),
                ('package_price', models.FloatField()),
                ('Price_per_day', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='no_of_persons',
            field=models.IntegerField(),
        ),
    ]
