# Generated by Django 2.2.6 on 2020-05-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0007_auto_20200505_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding_package',
            old_name='Price_per_day',
            new_name='Price_per_extra_day',
        ),
    ]
