# Generated by Django 2.2.6 on 2020-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0010_auto_20200506_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding_package',
            name='No_of_days',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
    ]
