# Generated by Django 2.2.6 on 2020-06-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0011_wedding_package_no_of_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=200)),
                ('person_capacity', models.IntegerField()),
                ('package_price', models.FloatField()),
                ('Price_per_extra_day', models.FloatField()),
                ('Price_per_extra_fifty_person', models.FloatField()),
                ('No_of_days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='wedding_package',
            name='No_of_days',
            field=models.IntegerField(),
        ),
    ]
